<h2>The Movie DB - List</h2>

<?php $movies = $block->getMovie();?>
<?php $search = $block->getPersonalSearch();?>

<form method="get" action="<?= $block->getMakeUrl("mundipagg_tmdb/movie/index");?>">
    <input name="search_tmdb" type="text" value="<?= (!empty($search))? $search : "";?>"/>
    <button type="submit">Search Movie.</button>
</form>

<?php if (!empty($movies->results)) :?>
    <?php foreach ($movies->results as $item): ?>
        <?php $movie = $block->objToTmdb($item)?>
        <div style="border: 1px solid black; width: 300px; float: left">
            <h3 style="height: 47px"><?=$movie->getTitle()?></h3>
            <p><img src="<?=$block->getImageBaseUrl($movie->getImageUrl())?>"></p>
            
            <form method="get" action="<?= $block->getMakeUrl("mundipagg_tmdb/movie/show");?>">
                <input name="tmdb_id" type="hidden" value="<?=$movie->getMovieId()?>"/>
                <button type="submit">See Description</button>
            </form>
        </div>
    <?php endforeach;?>
<?php endif; ?>